matrix:
  include:
    - os: linux
      language: cpp
      sudo: required
      dist: trusty
      services: docker
      install: docker pull rust:1
      script: docker run -v $(pwd):/liftinstall rust:1 /bin/bash -ex /liftinstall/.travis/build.sh

    - os: osx
      language: rust
      osx_image: xcode10
      script: brew install yarn && cargo build

    - os: windows
      language: rust
      script: choco install nodejs yarn && cargo build
