name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
        
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
        
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
    
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
